env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  indent:
    - 2
  import/extensions:
    - error
    - ignorePackages
    - js: always
